export default {
    USERNAME_MIN_LENGTH: 6,
    EMAIL_MIN_LENGTH: 6,
    FIRST_NAME_MIN_LENGTH: 2,
    LAST_NAME_MIN_LENGTH: 2,
    PASSWORD_MIN_LENGTH: 6,
    JOURNAL_TITLE_MIN_LENGTH: 4,
    JOURNAL_DESCRIPTION_MIN_LENGTH: 10,
    JOURNAL_LOCATION_MIN_LENGTH: 3,
}